### ISSUE TITLE
migration to sanic-wtf 0.4.0

### ISSUE THREAD

**Issue by pyx** [stopspazzing/Sanic-Server-with-MDL-Blog-Template#1]
As of Sanic-WTF 0.4.0, I removed `form.hidden_tag`, the csrf token is still accessible as `form.csrf_token` or whatever name you set in configuration.

The reason of removing this is here https://github.com/pyx/sanic-wtf/issues/9 , to put it simply, I figured that to have `hidden_tag` in the style of Flask-WTF (e.g, the same API, acts as a callable, including all hidden tags, etc.), we need another dependency (`markupsafe`) or roll our own wrapper.  I think it may not be worth it, so I decided to remove the misbehave `form.hidden_tag`.

Please correct me if I am wrong. Thanks.

**Comment by stopspazzing** [comment]
awesome, thanks for letting me know. Seems you may have been right, never fully tested it just added it cause I could. I'm updating my code. However, seems you broke `form.validate()` 😢

**Comment by pyx** [comment]
Could you elaborate what happen to `form.validate()`?  Much appreciated.

**Comment by pyx** [comment]
It may be related to the `request` object, the reasoning is here : https://github.com/pyx/sanic-wtf/issues/6 , in short, we have to somehow keep a copy of current request object, because Sanic is sharing threads among many routes (view functions), a thread-local request object does not work in this case, so I decided to have the whole `request` being passed in in form construction.

Please let me know if you have a better idea.  Thanks.

**Comment by pyx** [comment]
I think I know what you mean, in https://github.com/stopspazzing/Sanic-Server-with-MDL-Blog-Template/commit/1148a0f190e4193e1559bf0f7313b347b4106871
you removed the `{{ form.hidden_tag }}` call, but forgot to render the csrf token with `{{ form.csrf_token }}`

For CSRF protection to work, a hard-to-guess randomly-generated unique token is used with each request, the client should submit the token with other payloads to prove that the request is genuine.
The csrf token submission usually involve hidden field for normal HTML form submission, or special http header when using Restful API, in either way, the csrf token should be known by the client, that's why we need to rendered the hidden tag in the form (`{{ form.csrf_token }}`) to begin with.

You can learn more about CSRF [here](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)) and [here](https://en.wikipedia.org/wiki/Cross-site_request_forgery)

**Comment by pyx** [comment]
FYI, I just release 0.5.0 with file uploading support. Anything before that does not work well with file upload, unless you pass in the `request.files` explicitly.

**Comment by stopspazzing** [comment]
awesome, thanks. Going to be useful when i have to add uploading pictures. adding csrf now.

**Comment by stopspazzing** [comment]
crsf works properly, was my fault for not reading all of the docs. thanks.
