### ISSUE TITLE
What does config.cfg have to look like?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [stopspazzing/Sanic-Server-with-MDL-Blog-Template#3]
After installation on Windows7 with Sanic 0.4.1 and running `python main.py` I get this error:

```bash
Error - Config Not Found
...

```

**Comment by stopspazzing** [comment]
Actually pretty simple key;value pairs. So for each line could be something like this:
```
DEMO_CONTENT = False
SECRET_KEY = '45vam6iumLH#KHH%L3ls'
DATABASE = 'Driver=SQLite3;Database=mydatabase.db'
```
100% following Sanic's import from config:
http://sanic.readthedocs.io/en/latest/sanic/config.html#from-a-file

so either you can create a config file `config.cfg` file in same directory as `main.py` or you may load the program with the location of the file to variable config_file like so:
```
MY_SETTINGS=/path/to/config_file python3 main.py
```
Let me know if this makes sense or if you are still having problems. I also changed the error to a warning so makes more sense:
https://github.com/stopspazzing/Sanic-Server-with-MDL-Blog-Template/blob/master/main.py#L35

**Comment by Tset-Noitamotua** [comment]
After reading a bit of Sanic's docs you provided in link above it makes sense. For noobs like me having a dummy `config.cfg` and a link to the docs would be an easier start.

**Comment by stopspazzing** [comment]
@Tset-Noitamotua Completely understandable, I'll create a dummy config.cfg. I added information for loading config files to readme page.
